# Generated by Django 6.0 on 2025-12-08 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlerts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pc_id', models.CharField(blank=True, max_length=20, null=True)),
                ('camera_id', models.CharField(blank=True, max_length=10, null=True)),
                ('timestamp', models.DateTimeField()),
                ('level', models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('critical', 'critical')], max_length=10)),
                ('category', models.CharField(choices=[('fps', 'fps'), ('memory', 'memory'), ('gpu', 'gpu'), ('api', 'api'), ('camera', 'camera'), ('system', 'system')], max_length=20)),
                ('message', models.TextField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_alerts',
                'indexes': [models.Index(fields=['timestamp'], name='idx_timestamp'), models.Index(fields=['level'], name='idx_level'), models.Index(fields=['is_acknowledged', 'timestamp'], name='idx_unacknowledged')],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pc_id', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('cpu_temp_celsius', models.FloatField(blank=True, null=True)),
                ('cpu_fan_rpm', models.IntegerField(blank=True, null=True)),
                ('memory_percent', models.FloatField(blank=True, null=True)),
                ('memory_used_mb', models.FloatField(blank=True, null=True)),
                ('gpu_utilization', models.FloatField(blank=True, null=True)),
                ('gpu_memory_percent', models.FloatField(blank=True, null=True)),
                ('gpu_memory_used_mb', models.FloatField(blank=True, null=True)),
                ('gpu_temp_celsius', models.FloatField(blank=True, null=True)),
                ('gpu_fan_percent', models.FloatField(blank=True, null=True)),
                ('gpu_power_watts', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_metrics',
                'indexes': [models.Index(fields=['pc_id', 'timestamp'], name='idx_pc_timestamp')],
            },
        ),
        migrations.CreateModel(
            name='CameraMetrics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pc_id', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('fps', models.FloatField(blank=True, null=True)),
                ('avg_frame_time_ms', models.FloatField(blank=True, null=True)),
                ('avg_detection_time_ms', models.FloatField(blank=True, null=True)),
                ('avg_recognition_time_ms', models.FloatField(blank=True, null=True)),
                ('frames_processed', models.BigIntegerField(blank=True, null=True)),
                ('frames_dropped', models.BigIntegerField(blank=True, null=True)),
                ('faces_detected', models.IntegerField(blank=True, null=True)),
                ('faces_recognized', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('running', 'running'), ('paused', 'paused'), ('error', 'error'), ('stopped', 'stopped')], max_length=10, null=True)),
                ('camera', models.ForeignKey(db_column='camera_id', on_delete=django.db.models.deletion.CASCADE, to='cameras.tblcamera')),
            ],
            options={
                'db_table': 'camera_metrics',
                'indexes': [models.Index(fields=['camera', 'timestamp'], name='idx_camera_timestamp')],
            },
        ),
    ]
