# Generated by Django 6.0 on 2025-12-08 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=255)),
                ('person_nic', models.CharField(blank=True, max_length=20, null=True)),
                ('person_father', models.CharField(blank=True, max_length=255, null=True)),
                ('person_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('person_cat', models.CharField(blank=True, max_length=50, null=True)),
                ('person_embedding', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
