# Generated by Django 6.0 on 2025-12-11 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCConfiguration',
            fields=[
                ('pc_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pc_name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu_count', models.IntegerField(default=1)),
                ('gpu_ids', models.CharField(default='0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('error', 'error')], default='offline', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pc_configuration',
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('face_detection', 'face_detection'), ('face_recognition', 'face_recognition'), ('weapon_detection', 'weapon_detection')], max_length=30)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=20, null=True)),
                ('model_path', models.CharField(max_length=500)),
                ('model_format', models.CharField(choices=[('tensorrt', 'tensorrt'), ('onnx', 'onnx'), ('pytorch', 'pytorch')], default='tensorrt', max_length=20)),
                ('input_size', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ai_models',
                'indexes': [models.Index(fields=['model_type'], name='ai_models_model_t_608c1f_idx')],
                'unique_together': {('model_type', 'model_name', 'model_version')},
            },
        ),
        migrations.CreateModel(
            name='PcModelConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('face_detection', 'face_detection'), ('face_recognition', 'face_recognition'), ('weapon_detection', 'weapon_detection')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, to='core.aimodel')),
                ('pc', models.ForeignKey(db_column='pc_id', on_delete=django.db.models.deletion.CASCADE, to='core.pcconfiguration')),
            ],
            options={
                'db_table': 'pc_model_config',
                'unique_together': {('pc', 'model_type')},
            },
        ),
    ]
