# Generated by Django 6.0 on 2025-12-08 08:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblCamera',
            fields=[
                ('camera_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('attendance_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='IN', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tbl_camera',
            },
        ),
        migrations.CreateModel(
            name='CameraParameters',
            fields=[
                ('camera_id', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cameras.tblcamera')),
                ('ip_address', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('cam_type', models.CharField(choices=[('PTZ', 'PTZ'), ('Fixed', 'Fixed')], max_length=20)),
                ('fr_conf_thresh', models.FloatField(default=0.32)),
                ('fr_iou_thresh', models.FloatField(default=0.3)),
                ('fr_min_avg_thresh', models.FloatField(default=0.5)),
                ('fr_min_frame_count', models.IntegerField(default=10)),
                ('fr_min_frame_count_2', models.IntegerField(default=30)),
                ('fr_api_counter', models.IntegerField(default=1)),
                ('recognition_t', models.FloatField(default=0.32)),
                ('dist_method', models.CharField(choices=[('cosine', 'cosine'), ('euclidean', 'euclidean')], default='cosine', max_length=20)),
                ('norm_method', models.CharField(choices=[('fixed', 'fixed'), ('l2', 'l2')], default='fixed', max_length=20)),
                ('_sd', models.CharField(blank=True, max_length=50, null=True)),
                ('_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'camera_parameters',
            },
        ),
        migrations.CreateModel(
            name='CameraPreset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preset_token', models.CharField(max_length=10)),
                ('preset_name', models.CharField(blank=True, max_length=100, null=True)),
                ('preset_time', models.IntegerField(default=5)),
                ('preset_delay', models.IntegerField(default=0)),
                ('preset_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='cameras.tblcamera')),
            ],
            options={
                'db_table': 'camera_presets',
                'indexes': [models.Index(fields=['camera'], name='camera_pres_camera__d1acc6_idx'), models.Index(fields=['camera', 'preset_order'], name='camera_pres_camera__a49f27_idx')],
                'unique_together': {('camera', 'preset_token')},
            },
        ),
        migrations.CreateModel(
            name='CamPcConf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pc_id', models.CharField(max_length=20)),
                ('gpu_id', models.IntegerField(default=0)),
                ('enable_face_recognition', models.BooleanField(default=True)),
                ('enable_weapon_detection', models.BooleanField(default=False)),
                ('enable_tracking', models.BooleanField(default=True)),
                ('enable_live_stream', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cam', models.ForeignKey(db_column='cam_id', on_delete=django.db.models.deletion.CASCADE, to='cameras.tblcamera')),
            ],
            options={
                'db_table': 'cam_pc_conf',
                'indexes': [models.Index(fields=['pc_id', 'gpu_id'], name='cam_pc_conf_pc_id_8317a7_idx')],
                'unique_together': {('pc_id', 'cam')},
            },
        ),
    ]
