# Generated by Django 6.0 on 2025-12-08 08:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('in_time_start', models.TimeField()),
                ('in_time_end', models.TimeField()),
                ('out_time_start', models.TimeField(blank=True, null=True)),
                ('out_time_end', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'attendance_schedules',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=255)),
                ('pc_id', models.CharField(max_length=20)),
                ('attendance_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('camera', models.ForeignKey(db_column='camera_id', on_delete=django.db.models.deletion.CASCADE, to='cameras.tblcamera')),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
            ],
            options={
                'db_table': 'attendance_records',
                'indexes': [models.Index(fields=['person', 'date'], name='idx_person_date'), models.Index(fields=['date'], name='idx_date'), models.Index(fields=['camera', 'date'], name='idx_camera_date'), models.Index(fields=['attendance_type', 'date'], name='idx_type_date')],
            },
        ),
    ]
