# Generated by Django 6.0 on 2025-12-08 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('manager', 'manager'), ('viewer', 'viewer')], default='viewer', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('can_manage_persons', models.BooleanField(default=False)),
                ('can_manage_cameras', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('can_export_data', models.BooleanField(default=False)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
